# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kyuff.dk
email: soren@sxl.dk

#write html inside the double quotes to display in jumbotron
description: "<h3>&dash; notes from my work in software development."



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.kyuff.dk" # the base hostname & protocol for your site
twitter_username: kyuff
github_username:  kyuff

# Build settings
markdown: kramdown
